package de.e_nexus.vr.server;

/**
 * The keycodes.
 * 
 * @author Guest
 */
public enum ClientKeyboardScancode {
	UNKNOWN_SCANCODE_0, // The key on the keyboard of the vr-client's system having the scancode: 0
	UNKNOWN_SCANCODE_1, // The key on the keyboard of the vr-client's system having the scancode: 1
	UNKNOWN_SCANCODE_2, // The key on the keyboard of the vr-client's system having the scancode: 2
	UNKNOWN_SCANCODE_3, // The key on the keyboard of the vr-client's system having the scancode: 3
	UNKNOWN_SCANCODE_4, // The key on the keyboard of the vr-client's system having the scancode: 4
	UNKNOWN_SCANCODE_5, // The key on the keyboard of the vr-client's system having the scancode: 5
	UNKNOWN_SCANCODE_6, // The key on the keyboard of the vr-client's system having the scancode: 6
	UNKNOWN_SCANCODE_7, // The key on the keyboard of the vr-client's system having the scancode: 7
	BACK, // The key on the keyboard of the vr-client's system having the scancode: 8
	TAB, // The key on the keyboard of the vr-client's system having the scancode: 9
	UNKNOWN_SCANCODE_10, // The key on the keyboard of the vr-client's system having the scancode: 10
	UNKNOWN_SCANCODE_11, // The key on the keyboard of the vr-client's system having the scancode: 11
	UNKNOWN_SCANCODE_12, // The key on the keyboard of the vr-client's system having the scancode: 12
	ENTER, // The key on the keyboard of the vr-client's system having the scancode: 13
	UNKNOWN_SCANCODE_14, // The key on the keyboard of the vr-client's system having the scancode: 14
	UNKNOWN_SCANCODE_15, // The key on the keyboard of the vr-client's system having the scancode: 15
	SHIFT, // The key on the keyboard of the vr-client's system having the scancode: 16
	CTRL, // The key on the keyboard of the vr-client's system having the scancode: 17
	ALT, // The key on the keyboard of the vr-client's system having the scancode: 18
	PAUSE, // The key on the keyboard of the vr-client's system having the scancode: 19
	CAPSLOCK, // The key on the keyboard of the vr-client's system having the scancode: 20
	UNKNOWN_SCANCODE_21, // The key on the keyboard of the vr-client's system having the scancode: 21
	UNKNOWN_SCANCODE_22, // The key on the keyboard of the vr-client's system having the scancode: 22
	UNKNOWN_SCANCODE_23, // The key on the keyboard of the vr-client's system having the scancode: 23
	UNKNOWN_SCANCODE_24, // The key on the keyboard of the vr-client's system having the scancode: 24
	UNKNOWN_SCANCODE_25, // The key on the keyboard of the vr-client's system having the scancode: 25
	UNKNOWN_SCANCODE_26, // The key on the keyboard of the vr-client's system having the scancode: 26
	ESC, // The key on the keyboard of the vr-client's system having the scancode: 27
	UNKNOWN_SCANCODE_28, // The key on the keyboard of the vr-client's system having the scancode: 28
	UNKNOWN_SCANCODE_29, // The key on the keyboard of the vr-client's system having the scancode: 29
	UNKNOWN_SCANCODE_30, // The key on the keyboard of the vr-client's system having the scancode: 30
	UNKNOWN_SCANCODE_31, // The key on the keyboard of the vr-client's system having the scancode: 31
	SPACE, // The key on the keyboard of the vr-client's system having the scancode: 32
	PAGE_UP, // The key on the keyboard of the vr-client's system having the scancode: 33
	PAGE_DOWN, // The key on the keyboard of the vr-client's system having the scancode: 34
	END, // The key on the keyboard of the vr-client's system having the scancode: 35
	HOME, // The key on the keyboard of the vr-client's system having the scancode: 36
	LEFT, // The key on the keyboard of the vr-client's system having the scancode: 37
	UP, // The key on the keyboard of the vr-client's system having the scancode: 38
	RIGHT, // The key on the keyboard of the vr-client's system having the scancode: 39
	DOWN, // The key on the keyboard of the vr-client's system having the scancode: 40
	UNKNOWN_SCANCODE_41, // The key on the keyboard of the vr-client's system having the scancode: 41
	UNKNOWN_SCANCODE_42, // The key on the keyboard of the vr-client's system having the scancode: 42
	UNKNOWN_SCANCODE_43, // The key on the keyboard of the vr-client's system having the scancode: 43
	UNKNOWN_SCANCODE_44, // The key on the keyboard of the vr-client's system having the scancode: 44
	INSERT, // The key on the keyboard of the vr-client's system having the scancode: 45
	DELETE, // The key on the keyboard of the vr-client's system having the scancode: 46
	UNKNOWN_SCANCODE_47, // The key on the keyboard of the vr-client's system having the scancode: 47
	_0, // The key on the keyboard of the vr-client's system having the scancode: 48
	_1, // The key on the keyboard of the vr-client's system having the scancode: 49
	_2, // The key on the keyboard of the vr-client's system having the scancode: 50
	_3, // The key on the keyboard of the vr-client's system having the scancode: 51
	_4, // The key on the keyboard of the vr-client's system having the scancode: 52
	_5, // The key on the keyboard of the vr-client's system having the scancode: 53
	_6, // The key on the keyboard of the vr-client's system having the scancode: 54
	_7, // The key on the keyboard of the vr-client's system having the scancode: 55
	_8, // The key on the keyboard of the vr-client's system having the scancode: 56
	_9, // The key on the keyboard of the vr-client's system having the scancode: 57
	UNKNOWN_SCANCODE_58, // The key on the keyboard of the vr-client's system having the scancode: 58
	UNKNOWN_SCANCODE_59, // The key on the keyboard of the vr-client's system having the scancode: 59
	UNKNOWN_SCANCODE_60, // The key on the keyboard of the vr-client's system having the scancode: 60
	UNKNOWN_SCANCODE_61, // The key on the keyboard of the vr-client's system having the scancode: 61
	UNKNOWN_SCANCODE_62, // The key on the keyboard of the vr-client's system having the scancode: 62
	UNKNOWN_SCANCODE_63, // The key on the keyboard of the vr-client's system having the scancode: 63
	UNKNOWN_SCANCODE_64, // The key on the keyboard of the vr-client's system having the scancode: 64
	A, // The key on the keyboard of the vr-client's system having the scancode: 65
	B, // The key on the keyboard of the vr-client's system having the scancode: 66
	C, // The key on the keyboard of the vr-client's system having the scancode: 67
	D, // The key on the keyboard of the vr-client's system having the scancode: 68
	E, // The key on the keyboard of the vr-client's system having the scancode: 69
	F, // The key on the keyboard of the vr-client's system having the scancode: 70
	G, // The key on the keyboard of the vr-client's system having the scancode: 71
	H, // The key on the keyboard of the vr-client's system having the scancode: 72
	I, // The key on the keyboard of the vr-client's system having the scancode: 73
	J, // The key on the keyboard of the vr-client's system having the scancode: 74
	K, // The key on the keyboard of the vr-client's system having the scancode: 75
	L, // The key on the keyboard of the vr-client's system having the scancode: 76
	M, // The key on the keyboard of the vr-client's system having the scancode: 77
	N, // The key on the keyboard of the vr-client's system having the scancode: 78
	O, // The key on the keyboard of the vr-client's system having the scancode: 79
	P, // The key on the keyboard of the vr-client's system having the scancode: 80
	Q, // The key on the keyboard of the vr-client's system having the scancode: 81
	R, // The key on the keyboard of the vr-client's system having the scancode: 82
	S, // The key on the keyboard of the vr-client's system having the scancode: 83
	T, // The key on the keyboard of the vr-client's system having the scancode: 84
	U, // The key on the keyboard of the vr-client's system having the scancode: 85
	V, // The key on the keyboard of the vr-client's system having the scancode: 86
	W, // The key on the keyboard of the vr-client's system having the scancode: 87
	X, // The key on the keyboard of the vr-client's system having the scancode: 88
	Y, // The key on the keyboard of the vr-client's system having the scancode: 89
	Z, // The key on the keyboard of the vr-client's system having the scancode: 90
	SUPER_LEFT, // The key on the keyboard of the vr-client's system having the scancode: 91
	SUPER_RIGHT, // The key on the keyboard of the vr-client's system having the scancode: 92
	UNKNOWN_SCANCODE_93, // The key on the keyboard of the vr-client's system having the scancode: 93
	UNKNOWN_SCANCODE_94, // The key on the keyboard of the vr-client's system having the scancode: 94
	UNKNOWN_SCANCODE_95, // The key on the keyboard of the vr-client's system having the scancode: 95
	NUM0, // The key on the keyboard of the vr-client's system having the scancode: 96
	NUM1, // The key on the keyboard of the vr-client's system having the scancode: 97
	NUM2, // The key on the keyboard of the vr-client's system having the scancode: 98
	NUM3, // The key on the keyboard of the vr-client's system having the scancode: 99
	NUM4, // The key on the keyboard of the vr-client's system having the scancode: 100
	NUM5, // The key on the keyboard of the vr-client's system having the scancode: 101
	NUM6, // The key on the keyboard of the vr-client's system having the scancode: 102
	NUM7, // The key on the keyboard of the vr-client's system having the scancode: 103
	NUM8, // The key on the keyboard of the vr-client's system having the scancode: 104
	NUM9, // The key on the keyboard of the vr-client's system having the scancode: 105
	ASTERISK, // The key on the keyboard of the vr-client's system having the scancode: 106
	PLUS, // The key on the keyboard of the vr-client's system having the scancode: 107
	UNKNOWN_SCANCODE_108, // The key on the keyboard of the vr-client's system having the scancode: 108
	SUBSTRACT, // The key on the keyboard of the vr-client's system having the scancode: 109
	DECIMAL, // The key on the keyboard of the vr-client's system having the scancode: 110
	DIVIDE, // The key on the keyboard of the vr-client's system having the scancode: 111
	F1, // The key on the keyboard of the vr-client's system having the scancode: 112
	F2, // The key on the keyboard of the vr-client's system having the scancode: 113
	F3, // The key on the keyboard of the vr-client's system having the scancode: 114
	F4, // The key on the keyboard of the vr-client's system having the scancode: 115
	F5, // The key on the keyboard of the vr-client's system having the scancode: 116
	F6, // The key on the keyboard of the vr-client's system having the scancode: 117
	F7, // The key on the keyboard of the vr-client's system having the scancode: 118
	F8, // The key on the keyboard of the vr-client's system having the scancode: 119
	F9, // The key on the keyboard of the vr-client's system having the scancode: 120
	F10, // The key on the keyboard of the vr-client's system having the scancode: 121
	F11, // The key on the keyboard of the vr-client's system having the scancode: 122
	F12, // The key on the keyboard of the vr-client's system having the scancode: 123
	UNKNOWN_SCANCODE_124, // The key on the keyboard of the vr-client's system having the scancode: 124
	UNKNOWN_SCANCODE_125, // The key on the keyboard of the vr-client's system having the scancode: 125
	UNKNOWN_SCANCODE_126, // The key on the keyboard of the vr-client's system having the scancode: 126
	UNKNOWN_SCANCODE_127, // The key on the keyboard of the vr-client's system having the scancode: 127
	UNKNOWN_SCANCODE_128, // The key on the keyboard of the vr-client's system having the scancode: 128
	UNKNOWN_SCANCODE_129, // The key on the keyboard of the vr-client's system having the scancode: 129
	UNKNOWN_SCANCODE_130, // The key on the keyboard of the vr-client's system having the scancode: 130
	UNKNOWN_SCANCODE_131, // The key on the keyboard of the vr-client's system having the scancode: 131
	UNKNOWN_SCANCODE_132, // The key on the keyboard of the vr-client's system having the scancode: 132
	UNKNOWN_SCANCODE_133, // The key on the keyboard of the vr-client's system having the scancode: 133
	UNKNOWN_SCANCODE_134, // The key on the keyboard of the vr-client's system having the scancode: 134
	UNKNOWN_SCANCODE_135, // The key on the keyboard of the vr-client's system having the scancode: 135
	UNKNOWN_SCANCODE_136, // The key on the keyboard of the vr-client's system having the scancode: 136
	UNKNOWN_SCANCODE_137, // The key on the keyboard of the vr-client's system having the scancode: 137
	UNKNOWN_SCANCODE_138, // The key on the keyboard of the vr-client's system having the scancode: 138
	UNKNOWN_SCANCODE_139, // The key on the keyboard of the vr-client's system having the scancode: 139
	UNKNOWN_SCANCODE_140, // The key on the keyboard of the vr-client's system having the scancode: 140
	UNKNOWN_SCANCODE_141, // The key on the keyboard of the vr-client's system having the scancode: 141
	UNKNOWN_SCANCODE_142, // The key on the keyboard of the vr-client's system having the scancode: 142
	UNKNOWN_SCANCODE_143, // The key on the keyboard of the vr-client's system having the scancode: 143
	NUMLOCK, // The key on the keyboard of the vr-client's system having the scancode: 144
	SCROLLLOCK, // The key on the keyboard of the vr-client's system having the scancode: 145
	UNKNOWN_SCANCODE_146, // The key on the keyboard of the vr-client's system having the scancode: 146
	UNKNOWN_SCANCODE_147, // The key on the keyboard of the vr-client's system having the scancode: 147
	UNKNOWN_SCANCODE_148, // The key on the keyboard of the vr-client's system having the scancode: 148
	UNKNOWN_SCANCODE_149, // The key on the keyboard of the vr-client's system having the scancode: 149
	UNKNOWN_SCANCODE_150, // The key on the keyboard of the vr-client's system having the scancode: 150
	UNKNOWN_SCANCODE_151, // The key on the keyboard of the vr-client's system having the scancode: 151
	UNKNOWN_SCANCODE_152, // The key on the keyboard of the vr-client's system having the scancode: 152
	UNKNOWN_SCANCODE_153, // The key on the keyboard of the vr-client's system having the scancode: 153
	UNKNOWN_SCANCODE_154, // The key on the keyboard of the vr-client's system having the scancode: 154
	UNKNOWN_SCANCODE_155, // The key on the keyboard of the vr-client's system having the scancode: 155
	UNKNOWN_SCANCODE_156, // The key on the keyboard of the vr-client's system having the scancode: 156
	UNKNOWN_SCANCODE_157, // The key on the keyboard of the vr-client's system having the scancode: 157
	UNKNOWN_SCANCODE_158, // The key on the keyboard of the vr-client's system having the scancode: 158
	UNKNOWN_SCANCODE_159, // The key on the keyboard of the vr-client's system having the scancode: 159
	UNKNOWN_SCANCODE_160, // The key on the keyboard of the vr-client's system having the scancode: 160
	UNKNOWN_SCANCODE_161, // The key on the keyboard of the vr-client's system having the scancode: 161
	UNKNOWN_SCANCODE_162, // The key on the keyboard of the vr-client's system having the scancode: 162
	UNKNOWN_SCANCODE_163, // The key on the keyboard of the vr-client's system having the scancode: 163
	UNKNOWN_SCANCODE_164, // The key on the keyboard of the vr-client's system having the scancode: 164
	UNKNOWN_SCANCODE_165, // The key on the keyboard of the vr-client's system having the scancode: 165
	UNKNOWN_SCANCODE_166, // The key on the keyboard of the vr-client's system having the scancode: 166
	UNKNOWN_SCANCODE_167, // The key on the keyboard of the vr-client's system having the scancode: 167
	UNKNOWN_SCANCODE_168, // The key on the keyboard of the vr-client's system having the scancode: 168
	UNKNOWN_SCANCODE_169, // The key on the keyboard of the vr-client's system having the scancode: 169
	UNKNOWN_SCANCODE_170, // The key on the keyboard of the vr-client's system having the scancode: 170
	UNKNOWN_SCANCODE_171, // The key on the keyboard of the vr-client's system having the scancode: 171
	UNKNOWN_SCANCODE_172, // The key on the keyboard of the vr-client's system having the scancode: 172
	VOLUME_MUTE, // The key on the keyboard of the vr-client's system having the scancode: 173
	VOLUME_DOWN, // The key on the keyboard of the vr-client's system having the scancode: 174
	VOLUME_UP, // The key on the keyboard of the vr-client's system having the scancode: 175
	MEDIA_NEXT, // The key on the keyboard of the vr-client's system having the scancode: 176
	MEDIA_PREV, // The key on the keyboard of the vr-client's system having the scancode: 177
	MEDIA_STOP, // The key on the keyboard of the vr-client's system having the scancode: 178
	MEDIA_PLAY, // The key on the keyboard of the vr-client's system having the scancode: 179
	UNKNOWN_SCANCODE_180, // The key on the keyboard of the vr-client's system having the scancode: 180
	UNKNOWN_SCANCODE_181, // The key on the keyboard of the vr-client's system having the scancode: 181
	UNKNOWN_SCANCODE_182, // The key on the keyboard of the vr-client's system having the scancode: 182
	UNKNOWN_SCANCODE_183, // The key on the keyboard of the vr-client's system having the scancode: 183
	UNKNOWN_SCANCODE_184, // The key on the keyboard of the vr-client's system having the scancode: 184
	UNKNOWN_SCANCODE_185, // The key on the keyboard of the vr-client's system having the scancode: 185
	SEMICOLON, // The key on the keyboard of the vr-client's system having the scancode: 186
	EQUAL, // The key on the keyboard of the vr-client's system having the scancode: 187
	COMMA, // The key on the keyboard of the vr-client's system having the scancode: 188
	MINUS, // The key on the keyboard of the vr-client's system having the scancode: 189
	DOT, // The key on the keyboard of the vr-client's system having the scancode: 190
	SLASH, // The key on the keyboard of the vr-client's system having the scancode: 191
	QUOTA, // The key on the keyboard of the vr-client's system having the scancode: 192
	UNKNOWN_SCANCODE_193, // The key on the keyboard of the vr-client's system having the scancode: 193
	UNKNOWN_SCANCODE_194, // The key on the keyboard of the vr-client's system having the scancode: 194
	UNKNOWN_SCANCODE_195, // The key on the keyboard of the vr-client's system having the scancode: 195
	UNKNOWN_SCANCODE_196, // The key on the keyboard of the vr-client's system having the scancode: 196
	UNKNOWN_SCANCODE_197, // The key on the keyboard of the vr-client's system having the scancode: 197
	UNKNOWN_SCANCODE_198, // The key on the keyboard of the vr-client's system having the scancode: 198
	UNKNOWN_SCANCODE_199, // The key on the keyboard of the vr-client's system having the scancode: 199
	UNKNOWN_SCANCODE_200, // The key on the keyboard of the vr-client's system having the scancode: 200
	UNKNOWN_SCANCODE_201, // The key on the keyboard of the vr-client's system having the scancode: 201
	UNKNOWN_SCANCODE_202, // The key on the keyboard of the vr-client's system having the scancode: 202
	UNKNOWN_SCANCODE_203, // The key on the keyboard of the vr-client's system having the scancode: 203
	UNKNOWN_SCANCODE_204, // The key on the keyboard of the vr-client's system having the scancode: 204
	UNKNOWN_SCANCODE_205, // The key on the keyboard of the vr-client's system having the scancode: 205
	UNKNOWN_SCANCODE_206, // The key on the keyboard of the vr-client's system having the scancode: 206
	UNKNOWN_SCANCODE_207, // The key on the keyboard of the vr-client's system having the scancode: 207
	UNKNOWN_SCANCODE_208, // The key on the keyboard of the vr-client's system having the scancode: 208
	UNKNOWN_SCANCODE_209, // The key on the keyboard of the vr-client's system having the scancode: 209
	UNKNOWN_SCANCODE_210, // The key on the keyboard of the vr-client's system having the scancode: 210
	UNKNOWN_SCANCODE_211, // The key on the keyboard of the vr-client's system having the scancode: 211
	UNKNOWN_SCANCODE_212, // The key on the keyboard of the vr-client's system having the scancode: 212
	UNKNOWN_SCANCODE_213, // The key on the keyboard of the vr-client's system having the scancode: 213
	UNKNOWN_SCANCODE_214, // The key on the keyboard of the vr-client's system having the scancode: 214
	UNKNOWN_SCANCODE_215, // The key on the keyboard of the vr-client's system having the scancode: 215
	UNKNOWN_SCANCODE_216, // The key on the keyboard of the vr-client's system having the scancode: 216
	UNKNOWN_SCANCODE_217, // The key on the keyboard of the vr-client's system having the scancode: 217
	UNKNOWN_SCANCODE_218, // The key on the keyboard of the vr-client's system having the scancode: 218
	SQUARE_BRACKET_OPEN, // The key on the keyboard of the vr-client's system having the scancode: 219
	BACKSLASH, // The key on the keyboard of the vr-client's system having the scancode: 220
	SQUARE_BRACKET_CLOSE, // The key on the keyboard of the vr-client's system having the scancode: 221
	HASH, // The key on the keyboard of the vr-client's system having the scancode: 222
	CITE_OPEN, // The key on the keyboard of the vr-client's system having the scancode: 223
	UNKNOWN_SCANCODE_224, // The key on the keyboard of the vr-client's system having the scancode: 224
	UNKNOWN_SCANCODE_225, // The key on the keyboard of the vr-client's system having the scancode: 225
	UNKNOWN_SCANCODE_226, // The key on the keyboard of the vr-client's system having the scancode: 226
	UNKNOWN_SCANCODE_227, // The key on the keyboard of the vr-client's system having the scancode: 227
	UNKNOWN_SCANCODE_228, // The key on the keyboard of the vr-client's system having the scancode: 228
	UNKNOWN_SCANCODE_229, // The key on the keyboard of the vr-client's system having the scancode: 229
	UNKNOWN_SCANCODE_230, // The key on the keyboard of the vr-client's system having the scancode: 230
	UNKNOWN_SCANCODE_231, // The key on the keyboard of the vr-client's system having the scancode: 231
	UNKNOWN_SCANCODE_232, // The key on the keyboard of the vr-client's system having the scancode: 232
	UNKNOWN_SCANCODE_233, // The key on the keyboard of the vr-client's system having the scancode: 233
	UNKNOWN_SCANCODE_234, // The key on the keyboard of the vr-client's system having the scancode: 234
	UNKNOWN_SCANCODE_235, // The key on the keyboard of the vr-client's system having the scancode: 235
	UNKNOWN_SCANCODE_236, // The key on the keyboard of the vr-client's system having the scancode: 236
	UNKNOWN_SCANCODE_237, // The key on the keyboard of the vr-client's system having the scancode: 237
	UNKNOWN_SCANCODE_238, // The key on the keyboard of the vr-client's system having the scancode: 238
	UNKNOWN_SCANCODE_239, // The key on the keyboard of the vr-client's system having the scancode: 239
	UNKNOWN_SCANCODE_240, // The key on the keyboard of the vr-client's system having the scancode: 240
	UNKNOWN_SCANCODE_241, // The key on the keyboard of the vr-client's system having the scancode: 241
	UNKNOWN_SCANCODE_242, // The key on the keyboard of the vr-client's system having the scancode: 242
	UNKNOWN_SCANCODE_243, // The key on the keyboard of the vr-client's system having the scancode: 243
	UNKNOWN_SCANCODE_244, // The key on the keyboard of the vr-client's system having the scancode: 244
	UNKNOWN_SCANCODE_245, // The key on the keyboard of the vr-client's system having the scancode: 245
	UNKNOWN_SCANCODE_246, // The key on the keyboard of the vr-client's system having the scancode: 246
	UNKNOWN_SCANCODE_247, // The key on the keyboard of the vr-client's system having the scancode: 247
	UNKNOWN_SCANCODE_248, // The key on the keyboard of the vr-client's system having the scancode: 248
	UNKNOWN_SCANCODE_249, // The key on the keyboard of the vr-client's system having the scancode: 249
	UNKNOWN_SCANCODE_250, // The key on the keyboard of the vr-client's system having the scancode: 250
	UNKNOWN_SCANCODE_251, // The key on the keyboard of the vr-client's system having the scancode: 251
	UNKNOWN_SCANCODE_252, // The key on the keyboard of the vr-client's system having the scancode: 252
	UNKNOWN_SCANCODE_253, // The key on the keyboard of the vr-client's system having the scancode: 253
	UNKNOWN_SCANCODE_254, // The key on the keyboard of the vr-client's system having the scancode: 254

}
